query GET_HEALTH_CONFIDENCE_QUANTITIES {
  me {
    companies {
      quantities {
        keyResultsQuantity
        objectivesQuantity
        high
        medium
        low
        barrier
        achieved
        deprioritized
      }
    }
  }
}

query GET_HEALTH_CONFIDENCE_QUANTITIES_BY_TEAM($teamId: ID) {
  team(id: $teamId) {
    quantities {
      keyResultsQuantity
      objectivesQuantity
      high
      medium
      low
      barrier
      achieved
      deprioritized
    }
  }
}
