query GET_HEALTH_CONFIDENCE_QUANTITIES {
  me {
    companies {
      quantities {
        keyResultsQuantity
        objectivesQuantity
        high
        medium
        low
        barrier
        achieved
        deprioritized
      }
    }
  }
}
