query GET_KEYRESULTS_FOR_NOTIFICATIONS {
 me {
  keyResultsStatus {
    edges {
      node {
        title
        id
        teamId
        statuses {
          isOutdated
          latestCheckIn {
            createdAt
             user {
              fullName
            }
          }
        }
      }
    }
  }
}
}
