---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: execution-mode-stable
  labels:
    app.kubernetes.io/name: execution-mode-stable
    app.kubernetes.io/part-of: presentation-layer
    app.kubernetes.io/component: frontend-application
    app.kubernetes.io/version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: execution-mode-stable
  template:
    metadata:
      labels:
        app.kubernetes.io/name: execution-mode-stable
        app.kubernetes.io/part-of: presentation-layer
        app.kubernetes.io/component: frontend-application
        app.kubernetes.io/version: 1.0.0
    spec:
      containers:
        - name: execution-mode-app
          image: 904333181156.dkr.ecr.sa-east-1.amazonaws.com/execution-mode:$ECR_TAG
          ports:
            - containerPort: 8080
          env:
            - name: APP_ENV
              value: production
            - name: HOST
              value: app.getbud.co
            - name: PORT
              value: '8080'
            - name: DEFAULT_LOCALE
              value: pt-BR
            - name: SUPPORTED_LOCALES
              value: pt-BR,en-US
            - name: API_GRAPHQL
              value: https://api.getbud.co/business/graphql
            - name: AUTH0_CLIENT_ID_PUBLIC
              value: 76DivGrWIbmLh7V2SkFyPeIbUFN6OBf3
            - name: AUTH0_DOMAIN
              value: auth.getbud.co
            - name: AUTH0_SCOPE
              value: openid profile
            - name: AUTH0_AUDIENCE
              value: https://api.getbud.co/business
            - name: MAINTENANCE_MODE_ENABLED
              value: 'false'
            - name: MAINTENANCE_MODE_EXPECTED_RETURN
              value: 2021-03-26T21:00:00Z
            - name: HOTJAR_ID
              value: '2216269'
            - name: HOTJAR_SV
              value: '6'
            - name: SMARTLOOK_API_KEY
              value: '5cab2cdecc225119adeece5e90353c122c462d14'
            - name: AMPLITUDE_API_KEY
              value: 9314f6f12a26e6a5989287b16d030c30
