mutation CREATE_CHECK_MARK($keyResultID: ID!, $description: String!) {
  createKeyResultCheckMark(data: { keyResultId: $keyResultID, description: $description }) {
    id
    description
    state
    policy {
      update
    }
  }
}

mutation DELETE_CHECK_MARK($id: ID!) {
  deleteCheckMark(id: $id) {
    affected
  }
}

mutation UPDATE_ASSIGNED_CHECKMARK($checkMarkId: ID!, $assignedUserId: ID!) {
  updateCheckMarkAssignee(id: $checkMarkId, data: { assignedUserId: $assignedUserId }) {
    id
  }
}
