mutation UPDATE_KEY_RESULT_GOAL_AND_INITIAL_VALUE($id: ID!, $initialValue: number, $goal: number) {
  updateKeyResult(id: $id, data: {
    initialValue: $initialValue,
    goal: $goal
  }) {
    id
    initialValue
    goal
  }
}