query GET_USER_PRIMARY_COMPANY {
  me {
    companies(limit: 1) {
      id
      name
      gender
      percentageProgressIncrease
      latestReport {
        id
        createdAt
        user {
          id
          name
        }
      }
    }
  }
}
