query GET_USER_PRIMARY_COMPANY {
  me {
    companies(limit: 1) {
      id
      name
      gender
      progress
      confidence
      progressIncreaseSinceLastWeek
      latestKeyResultCheckIn {
        id
        createdAt
        user {
          id
          fullName
        }
      }
    }
  }
}
