image:
  file: .gitpod.Dockerfile

tasks:
  - name: Apply GPG keys
    before: >
      [[ ! -z $GNUGPG  ]] &&
      cd ~ &&
      rm -rf .gnupg &&
      echo $GNUGPG | base64 -d | tar --no-same-owner -xzvf -
      
  - name: Development Server
    init: npm install
    command: npm run start:dev

ports:
  - port: 3000
