image:
  file: .gitpod.Dockerfile

tasks:
  - name: Apply GPG keys
    before: >
      [[ ! -z $GNUPG  ]] &&
      [[ ! -z $GNUPG_KEY_ID  ]] &&
      cd ~ &&
      rm -rf .gnupg &&
      echo $GNUPG | base64 -d | tar --no-same-owner -xzvf - &&
      git config --global user.signingkey $GNUGPG_PUB_ID &&
      git config --global commit.gpgsign true
      
  - name: Server
    init: >
      npm install &&
      source <(grep -v '^#' .env | sed -E 's|^(.+)=(.*)$|: ${\1=\2}; export \1|g') &&
      export URL=$(gp url 3000)
    command: npm run start:dev

ports:
  - port: 3000
