query GET_OBJECTIVE_KEY_RESULTS($objectiveID: ID!) {
  objective(id: $objectiveID) {
    id
    keyResults {
      edges {
        node {
          id
          title
          format
          type
          goal
          initialValue
          status {
            isOutdated
            latestKeyResultCheckIn {
              id
              value
              confidence
              progress
              createdAt
            }
          }
          owner {
            id
            firstName
            fullName
            nickname
            picture
            role
            about
            linkedInProfileAddress
            teams {
              edges {
                node {
                  id
                  name
                }
              }
            }
          }
          team {
            name
          }
          objective {
            cycle {
              period
              dateStart
              dateEnd
            }
          }
          policy {
            update
            delete
          }
          keyResultCheckIns {
            policy {
              create
            }
          }
        }
      }
    }
  }
}
