mutation UPDATE_OBJECTIVE($objectiveID: ID!, $title: String!, $description: String) { updateObjective(id: $objectiveID, data: {
    title: $title,
    description: $description
  }) {
    id
    title
    description
  }
}
