query GET_ROOT_TEAMS_AND_COMPANIES {
  teams(parentTeamId: null) {
    id
    name
    description
    teams {
      keyResults {
        owner {
          picture
        }
        progressReports(limit: 1) {
          valueNew
        }
      }
    }
  }

  companies {
    id
    name
    description
    teams {
      keyResults {
        progressReports(limit: 1) {
          valueNew
        }
      }
    }
  }
}
