query GET_TEAM_AND_CHILD_TEAMS_OBJECTIVES($rootTeamId: ID!) {
  team(id: $rootTeamId) {
    id
    name
    objectives {
      id
      title
      progressIncreaseSinceLastWeek
      cycle {
        dateEnd
      }
      status {
        progress
        confidence
      }
    }
    teams {
      id
      name
      objectives {
        id
        title
        progressIncreaseSinceLastWeek
        cycle {
          dateEnd
        }
        status {
          progress
          confidence
        }
      }
    }
  }
}
