query GET_TEAM_AND_CHILD_TEAMS_OBJECTIVES($rootTeamId: ID!) {
  team(id: $rootTeamId) {
    id
    name
    objectives {
      id
      title
      progress
      confidence
      progressIncreaseSinceLastWeek
      cycle {
        dateEnd
      }
    }
    teams {
      id
      name
      objectives {
        id
        title
        progress
        confidence
        progressIncreaseSinceLastWeek
        cycle {
          dateEnd
        }
      }
    }
  }
}
