query GET_TEAMS {
  teams(filters: { onlyCompaniesAndDepartments: true }) {
    id
    name
    description
    isCompany
    users {
      fullName
      picture
    }
    status {
      progress
      confidence
    }
  }
}
