query GET_TEAMS {
  teams(first: 1000) {
    edges {
      node {
        policy {
          update
        }
        id
        name
        description
        isCompany
        ownerId
        owner {
          id
          fullName
        }
        parent {
          id
          name
        }
        users {
          edges {
            node {
              fullName
              picture
            }
          }
        }
        status {
          progress
          confidence
        }
      }
    }
  }
}
