query GET_USER_NAME_AND_GENDER_AND_SETTINGS {
  me {
    id
    firstName
    gender
    picture
    role
    settings {
      edges {
        node {
          preferences
        }
      }
    }
    companies {
      edges {
        node {
          id
        }
      }
    }
  
    teams_status {
      edges {
        node {
          name
          id
          status {
            progress
            confidence
            latestCheckIn {
              createdAt
              user {
                fullName
              }
            }
          }
      delta {
        progress
      }
      tacticalCycle {
        dateStart
        dateEnd
      }
    }
          }
      }
    }
  
}
