query GET_CYCLES_STATUS {
  me {
    companies(first: 1) {
      edges {
        node {
          id
          cycles {
            edges {
              node {
                id
                period
                cadence
                active
                dateStart
                dateEnd
                parentId     
                teamId
              }
            }
          }
        }
      }
    }
  }
}
