mutation UPDATE_USER_MAIN_TEAM($userID: ID!, $main_team_id: String!) {
  updateMainTeam(userID: $userID, main_team_id: $main_team_id) {
    preferences
  }
}

query GET_TEAM_WITH_ID($teamId: ID!) {
  team(id: $teamId) {
    name
    id
    status {
            progress
            confidence
            latestCheckIn {
              createdAt
              user {
                fullName
              }
            }
          }
      delta {
        progress
      }
      tacticalCycle {
        dateStart
        dateEnd
      }
  }
}

