query GET_TEAM_INDICATORS($teamId: ID!, $allUsers: Boolean) {
  team(id: $teamId) {
    users(withIndicators: true,allUsers: $allUsers) {
      edges {
        node {
          id
          userIndicators {
            keyResultsProgress {
              progress
              delta {
                progress
                confidence
              }
              latestCheckIn {
                createdAt
              }
            }
            keyResultsCheckInProgress {
              checked
              total
            }
            keyResultsCheckListProgress {
              checked
              total
            }
          }
          amplitude {
            last_used
          }

          lastRoutine {
            id
            userId
            answers {
              questionId
              answerGroupId
              value
            }
          }
        }
      }
    }
  }
}
