mutation CREATE_KEY_RESULT(
  $title: String!
  $initialValue: Float!
  $goal: Float!
  $format: KeyResultFormat!
  $ownerID: ID!
  $objectiveID: ID!
  $teamID: ID
  $type: KeyResultType
  $description: String
) {
  createKeyResult(
    data: {
      title: $title
      initialValue: $initialValue
      goal: $goal
      format: $format
      ownerId: $ownerID
      objectiveId: $objectiveID
      teamId: $teamID
      type: $type
      description: $description
    }
  ) {
    id
  }
}

mutation UPDATE_KEY_RESULT(
  $id: ID!
  $title: String
  $description: String
  $format: KeyResultFormat
  $initialValue: Float
  $goal: Float
  $ownerID: ID
) {
  updateKeyResult(
    id: $id
    data: {
      title: $title
      description: $description
      format: $format
      initialValue: $initialValue
      goal: $goal
      ownerId: $ownerID
    }
  ) {
    title
    description
    format
    initialValue
    goal
    ownerId
  }
}
