mutation CREATE_KEY_RESULT_CHECK_IN($keyResultCheckInInput: KeyResultCheckInInput!) {
  createKeyResultCheckIn(data: $keyResultCheckInInput) {
    id
    value
    confidence
    progress
    comment
    createdAt
    keyResultId
    delta {
      value
    }
    parent {
      confidence
      progress
    }
    policy {
      delete
    }
  }
}
