mutation CREATE_KEY_RESULT_CHECK_IN($keyResultCheckInInput: KeyResultCheckInInput!) {
  createKeyResultCheckIn(keyResultCheckIn: $keyResultCheckInInput) {
    id
    value
    confidence
    progress
    comment
    createdAt
    keyResultId
    parent {
      confidence
      progress
    }
    policies {
      delete
    }
  }
}
