mutation CREATE_KEY_RESULT_CHECK_IN($keyResultCheckInInput: KeyResultCheckInInput!) {
  createKeyResultCheckIn(keyResultCheckIn: $keyResultCheckInInput) {
    id
    confidence
    relativePercentageProgress
    comment
    createdAt
    keyResultId
    parent {
      confidence
      relativePercentageProgress
    }
    policies {
      delete
    }
  }
}
