query GET_USER_NAMED_AVATAR_DATA {
  me {
    id
    firstName
    fullName
    picture
    email
    gender
    role
    createdAt
    yearlyProgress
    quarterlyProgress
    companies(first: 1) {
      edges {
        node {
          id
          name
        }
      }
    }
    teams {
      edges {
        node {
          id
          name
        }
      }
    }
  }
}
