# @deprecated in favor of shared query GET_MYSELF
query GET_USER_NAMED_AVATAR_DATA {
  me {
    id
    firstName
    fullName
    picture
    email
    gender
    role
    isTeamLeader
    createdAt
    yearlyProgress {
      showProgress
      progress
    }
    quarterlyProgress {
      showProgress
      progress
    }
    companies(first: 1) {
      edges {
        node {
          id
          name
          gender
        }
      }
    }
    teams {
      edges {
        node {
          id
          name
        }
      }
    }
  }
}
