query GET_TEAM_ACTIVE_OBJECTIVES($teamID: ID!) {
  team(id: $teamID) {
    id
    name
    objectives(active: true) {
      edges {
        node {
          id
          title
          progressIncreaseSinceLastWeek
          cycle {
            id
            period
            cadence
            dateEnd
          }
          status {
            progress
            confidence
          }
          policy {
            update
          }
        }
      }
    }
  }
}
