query GET_TEAM_ACTIVE_OBJECTIVES($teamID: ID!) {
  team(id: $teamID) {
    id
    name
    activeObjectives: allObjectives(active: true) {
       edges {
        node {
          id
          title
          cycle {
            id
            period
            cadence
            dateEnd
          }
          status {
            progress
            confidence
          }
          delta {
            progress
          }
          policy {
            update
            delete
          }
        }
      }
      policy {
        create
      }
    }
    notActiveObjectives: allObjectives(active: false, first: 1) {
      edges {
        node {
          id
        }
      }
    }
  }
}