query GET_KEY_RESULT_VIEW_WITH_BINDING($binding: KEY_RESULT_CUSTOM_LIST_BINDING!) {
  keyResultCustomList(binding: $binding) {
    id
    rank
    keyResults {
      id
      title
      initialValue
      goal
      format
      team {
        name
      }
      objective {
        title
        cycle {
          name
          dateStart
          dateEnd
        }
      }
      owner {
        id
        fullName
        picture
        role
      }
      latestKeyResultCheckIn {
        id
        value
        confidence
        progress
        comment
        createdAt
        user {
          fullName
        }
      }
    }
  }
}

mutation UPDATE_RANK($id: ID!, $keyResultCustomListInput: KeyResultCustomListInput!) {
  updateKeyResultCustomList(id: $id, keyResultCustomListInput: $keyResultCustomListInput) {
    id
  }
}
