query KeyResultViewForBinding($binding: KeyResultViewBinding!) {
  keyResultView(binding: $binding) {
    id
    rank
    keyResults {
      id
      title
      team {
        name
      }
      objective {
        title
        cycle {
          dateStart
          dateEnd
        }
      }
      owner {
        name
        picture
        role
      }
      progressReports(limit: 1) {
        id
        valueNew
      }
      confidenceReports(limit: 1) {
        id
        valueNew
        comment
        createdAt
      }
    }
  }
}
