query GET_ROOT_TEAMS_AND_COMPANIES {
  teams(parentTeamId: null) {
    id
    name
    description
    currentProgress
    currentConfidence
    users {
      name
      picture
    }
  }

  companies {
    id
    name
    description
    currentProgress
    currentConfidence
    users {
      name
      picture
    }
  }
}

query GET_CHILD_TEAMS_OBJECTIVES($rootTeamId: ID!) {
  team(id: $rootTeamId) {
    teams {
      name
      objectives {
        id
        title
        currentProgress
        currentConfidence
        cycle {
          dateEnd
        }
      }
    }
  }
}

query GET_TEAM_NAME($teamId: ID!) {
  team(id: $teamId) {
    id
    name
  }
}
