query GET_ROOT_TEAMS_AND_COMPANIES {
  teams(parentTeamId: null) {
    id
    name
    description
    currentProgress
    currentConfidence
    teams {
      keyResults {
        owner {
          picture
        }
      }
    }
  }

  companies {
    id
    name
    description
    currentProgress
    currentConfidence
    teams {
      keyResults {
        owner {
          picture
        }
      }
    }
  }
}
