query GET_OBJECTIVE_KEY_RESULTS($objectiveID: ID!, $withTeams: Boolean! = true) {
  objective(id: $objectiveID) {
    id
    keyResults(order: { createdAt: ASC }) {
      edges {
        node {
          id
          title
          format
          mode
          type
          teamId
          delta {
            progress
          }
          goal
          initialValue
          status {
            isOutdated
            isActive
            latestCheckIn {
              id
              value
              confidence
              progress
              createdAt
            }
          }
          owner {
            id
            firstName
            fullName
            nickname
            picture
            role
            about
            linkedInProfileAddress
            teams {
              edges {
                node {
                  id
                  name
                }
              }
            }
          }
          team @include(if: $withTeams) {
            name
          }
          objective {
            cycle {
              period
              dateStart
              dateEnd
            }
          }
          policy {
            update
            delete
          }
          keyResultCheckIns {
            policy {
              create
            }
          }
          supportTeamMembers {
            edges {
              node {
                id
                fullName
                picture
              }
            }
          }
        }
      }
    }
  }
}



mutation UPDATE_DRAFT_OBJECTIVE($objectiveID: ID!, $mode: String!) { updateObjective(id: $objectiveID, data: {
    mode: $mode,
  }) {
    id
    mode
  }
}
