mutation UPDATE_KEY_RESULT_OWNER($keyResultID: ID!, $userID: ID!) {
  updateKeyResult(id: $keyResultID, data: {
    ownerId: $userID
  }) {
    id
    ownerId
    owner {
      id
      firstName
      fullName
      nickname
      picture
      role
      about
      linkedInProfileAddress
      teams {
        edges {
          node {
            id
            name
          }
        }
      }
    }
    policy {
      update
    }
  }
}

mutation UPDATE_KEY_RESULT_SUPPORT_TEAM($keyResultID: ID!, $supportTeam: [ID]!) {
  updateKeyResult(id: $keyResultID, data: {
    supportTeam: $supportTeam
  }) {
    id
    supportTeam {
      edges {
        node {
          id
          name
        }
      }
    }
    policy {
      update
    }
  }
}