mutation CREATE_CYCLE(
  $teamId: ID!
  $period: String!
  $cadence: Cadence!
  $dateStart: DateTime!
  $dateEnd: DateTime!
  $active: Boolean!
  $parentId: String!
) {
  createCycle(
    data: {
      teamId: $teamId
      period: $period
      cadence: $cadence
      dateStart: $dateStart
      dateEnd: $dateEnd
      active: $active
      parentId: $parentId
    }
  ) {
    id
    period
    cadence
    dateStart
    dateEnd
    active
    parentId
  }
}
