version: '3.7'

services:
  dev-app:
    image: mcr.microsoft.com/vscode/devcontainers/typescript-node:14
    command: tail -f /dev/null
    env_file:
      - ../.env
      - ../.env.development
    volumes:
      - ..:/workspace:cached
