version: '3.7'

services:
  dev-app:
    image: mcr.microsoft.com/vscode/devcontainers/typescript-node:14
    command: tail -f /dev/null
    network_mode: host
    env_file: .env
    volumes:
      - ..:/workspace:cached