mutation CREATE_DRAFT_OBJECTIVE($title: String!, $teamID: ID!, $cycleID: ID! $ownerID: ID!) {
  createObjective(data: {
    title: $title,
    teamId: $teamID,
    cycleId: $cycleID,
    ownerId: $ownerID,
  }) {
    id
    title
    cycle {
      id
      period
      cadence
      dateEnd
    }
    status {
      progress
      confidence
    }
    delta {
      progress
    }
    policy {
      update
      delete
    }
  }
}
