query GET_TEAM_NAME($teamId: ID!) {
  team(id: $teamId) {
    id
    name
    description
    status {
      progress
    }
    users {
      edges {
        node {
          id
          fullName
          role
          picture
        }
      }
    }
  }
}
