query GET_TEAM_DATA($teamId: ID!) {
  team(id: $teamId) {
    id
    name
    description
    status {
      progress
    }
    keyResults {
      policy {
        create
      }
    }
    users(first: 1000) {
      edges {
        node {
          id
          firstName
          nickname
          fullName
          role
          picture
          about
          linkedInProfileAddress
        }
      }
      policy {
        create
      }
    }
    teams {
      edges {
        node {
          id
          name
          status {
            progress
          }
        }
      }
    }
  }
}
