mutation CREATE_USER(
  $firstName: String!
  $lastName: String!
  $email: String!
  $role: String
  $gender: UserGender!
  $teamID: ID!
  $locale: String
) {
  createUser(
    data: {
      firstName: $firstName
      lastName: $lastName
      email: $email
      role: $role
      gender: $gender
      teamID: $teamID
      locale: $locale
    }
  ) {
    id
    gender
  }
}

query GET_USER_LOCALE($userID: ID!) {
  user(id: $userID) {
    settings(keys: [LOCALE]) {
      edges {
        node {
          value
        }
      }
    }
  }
}
