query GET_COMPANY_TEAMS {
  teams(level: COMPANY) {
    edges {
      node {
        id
        rankedDescendants {
          edges {
            node {
              id
              name
              status {
                progress
                confidence
                latestCheckIn {
                  createdAt
                }
              }
              delta {
                progress
              }
              tacticalCycle {
                dateStart
                dateEnd
              }
            }
          }
        }
      }
    }
  }
}
