query GET_COMPANY_TEAMS {
  teams(level: COMPANY) {
    edges {
      node {
        id
        rankedTeams {
          edges {
            node {
              id
              name
              progressIncreaseSinceLastWeek
              status {
                progress
                confidence
              }
            }
          }
        }
      }
    }
  }
}
