query GET_COMPANY_CYCLES {
  me {
    companies(first: 1) {
      edges {
        node {
          id
          cycles(active: true) {
            edges {
              node {
                id
                period
                cadence
                dateStart
                dateEnd
                active
                delta {
                  progress
                }
                status {
                  progress
                  confidence
                  latestCheckIn {
                    id
                    createdAt
                    user {
                      id
                      fullName
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
