query GET_TEAM_NOT_ACTIVE_OBJECTIVES($teamID: ID!) {
  team(id: $teamID) {
    id
    name
    allObjectives(active: false) {
      edges {
        node {
          id
          title
          cycle {
            id
            period
            cadence
            dateEnd
            parent {
              id
              period
              cadence
            }
          }
          status {
            progress
          }
        }
      }
    }
  }
}
