---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: execution-mode-canary
  labels:
    app.kubernetes.io/name: execution-mode-canary
    app.kubernetes.io/part-of: presentation-layer
    app.kubernetes.io/component: frontend-application
    app.kubernetes.io/version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: execution-mode-canary
  template:
    metadata:
      labels:
        app.kubernetes.io/name: execution-mode-canary
        app.kubernetes.io/part-of: presentation-layer
        app.kubernetes.io/component: frontend-application
        app.kubernetes.io/version: 1.0.0
    spec:
      containers:
        - name: execution-mode-app
          image: 904333181156.dkr.ecr.sa-east-1.amazonaws.com/execution-mode:$ECR_TAG
          ports:
            - containerPort: 8080
          env:
            - name: APP_ENV
              value: develop
            - name: APP_VERSION
              value: $ECR_TAG
            - name: HOST
              value: app.canary.getbud.co
            - name: PORT
              value: '8080'
            - name: DEFAULT_LOCALE
              value: pt-BR
            - name: SUPPORTED_LOCALES
              value: pt-BR,en-US
            - name: API_GRAPHQL
              value: https://api.canary.getbud.co/business/graphql
            - name: AUTH0_CLIENT_ID_PUBLIC
              value: 76DivGrWIbmLh7V2SkFyPeIbUFN6OBf3
            - name: AUTH0_DOMAIN
              value: auth.getbud.co
            - name: AUTH0_SCOPE
              value: openid profile
            - name: AUTH0_AUDIENCE
              value: https://api.getbud.co/business
            - name: AUTH0_API_DOMAIN
              value: https://api.getbud.co
            - name: HOTJAR_ID
              value: '2216269'
            - name: HOTJAR_SV
              value: '6'
            - name: SMARTLOOK_API_KEY
              value: '5cab2cdecc225119adeece5e90353c122c462d14'
            - name: AMPLITUDE_API_KEY
              value: 9314f6f12a26e6a5989287b16d030c30
            - name: NO_GAMIFICATION_COMPANIES_IDS
              value: '96eeb274-518e-462a-a741-f304420aa637'
            - name: TIMELINE_COMPANIES_IDS
              value: '96eeb274-518e-462a-a741-f304420aa637'
