---
kind: Service
apiVersion: v1
metadata:
  name: execution-mode-app
  labels:
    app.kubernetes.io/name: execution-mode-app
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: execution-mode
    app.kubernetes.io/part-of: presentation-layer
spec:
  selector:
    app.kubernetes.io/name: execution-mode-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
