query GET_USER_DATA($id: ID!) {
  user(id: $id) {
    id
    firstName
    lastName
    fullName
    email
    role
    nickname
    gender
    about
    picture
    linkedInProfileAddress
    teams {
      edges {
        node {
          id
          name
        }
      }
    }
    policy {
      update
      delete
    }
  }
}
