mutation CREATE_TEAM($name: String!, $description: String!, $gender: TeamGender!, $ownerID: ID!, $parentID: ID!) {
  createTeam(data: {
    name: $name,
    description: $description,
    gender: $gender,
    ownerID: $ownerID,
    parentID: $parentID,
  }) {
    id
  }
}

mutation UPDATE_TEAM($id: ID!,$name: String, $description: String, $ownerId: ID, $parentId: ID) {
  updateTeam(id: $id, 
    data: {
      description: $description, 
      name: $name, 
      ownerId: $ownerId, 
      parentId: $parentId
    }) {
    id
  }
}
