mutation CREATE_TEAM($name: String!, $description: String!, $teamGender: TeamGender! $parentID: ID!) {
  createObjective(data: {
    name: $name,
    description: $description,
    teamGender: $TeamGender,
    parentId: $parentID,
  }) {
    name
    description
    teamGender
    delta {
      progress
    }
    policy {
      update
      delete
    }
  }
}
