query GET_KEY_RESULT_VIEW_WITH_BINDING($binding: KeyResultViewBinding!) {
  keyResultView(binding: $binding) {
    id
    rank
    keyResults {
      id
      title
      initialValue
      goal
      format
      currentProgress
      team {
        name
      }
      objective {
        title
        cycle {
          dateStart
          dateEnd
        }
      }
      owner {
        name
        picture
        role
      }
      confidenceReports(limit: 1) {
        id
        valueNew
        comment
        createdAt
      }
    }
  }
}

mutation UPDATE_RANK($id: ID!, $rankInput: KeyResultViewRankInput!) {
  updateRank(id: $id, keyResultViewRankInput: $rankInput) {
    id
  }
}
