export enum EventType {
  PAGE_VIEW = 'PageView',
  KEY_RESULT_PROGRESS_CHART_VIEW = 'KeyResultProgressChartView',
  KEY_RESULT_CREATE_CHECKLIST = 'KeyResultCreateCheckList',
  OPENED_KEY_RESULT_DRAWER = 'OpenedKeyResultDrawer',
  OPENED_KEY_RESULT_CHECKLIST = 'OpenedKeyResultChecklist',
  TOGGLED_KEY_RESULT_CHECK_MARK = 'ToggledKeyResultCheckMark',
  UPDATED_KEY_RESULT_CHECK_MARK_TITLE = 'UpdatedKeyResultCheckMarkTitle',
  DELETED_KEY_RESULT_CHECK_MARK = 'DeletedKeyResultCheckMark',
  UPDATED_KEY_RESULT_CHECK_MARK_ASSIGNEE = 'UpdatedKeyResultCheckMarkAssignee',
  CREATED_KEY_RESULT_CHECK_MARK = 'CreatedKeyResultCheckMark',
  CREATED_KEY_RESULT_CHECK_IN = 'CreatedKeyResultCheckIn',
  CREATED_KEY_RESULT_COMMENT = 'CreatedKeyResultComment',
  CREATED_PERSONAL_TASK = 'CreatedPersonalTask',
  DELETED_PERSONAL_TASK = 'DeletedPersonalTask',
  TOGGLED_PERSONAL_TASK = 'ToggledPersonalTask',
  UPDATED_PERSONAL_TASK_TITLE = 'UpdatedPersonalTaskTitle',
  OPENED_KEY_RESULT_REPORT_CONFIDANCE = 'OpenedKeyResultReportConfidance',
}
