export enum NOTIFICATIONS_TYPE {
  LOW_CONFIDENCE = 'low-confidence',
  CONFIDENCE_BARRIER = 'barrier',
  ASSIGNED_TASK = 'taskAssign',
  ADD_SUPPORT_TEAM = 'supportTeam',
  TAGGED_COMMENT = 'taggedInComment',
  COMMENT_ON_MY_KR = 'commentOnKR',
  COMMENT_ON_MY_ROUTINE = 'commentOnRoutine',
  MENTION_ON_MY_ROUTINE = 'mentionOnRoutine',
  KR_FEEDBACK = 'mentionOnRoutine',
  KR_OWNER = 'mentionOnRoutine',
  ASSIGNED_TASK_IN_PROJECT = 'taskAssignInProject',
  COMMENT_ON_TASK = 'commentOnTask',
  MENTION_ON_TASK = 'mentionOnTask',
}
