export enum NOTIFICATIONS_TYPE {
  LOW_CONFIDENCE = 'LOW_CONFIDENCE',
  CONFIDENCE_BARRIER = 'BARRIER',
  ASSIGNED_TASK = 'ASSIGNED_TASK',
  ADD_SUPPORT_TEAM = 'ADD_SUPPORT_TEAM',
  TAGGED_COMMENT = 'TAGGED_COMMENT',
  COMMENT_ON_MY_KR = 'COMMENT_ON_MY_KR',
}
