import { COLOR_SCHEME } from 'src/themes/tokens'

export enum SIGNAL {
  POSITIVE = 'positive',
  NEGATIVE = 'negative',
  NEUTRAL = 'neutral',
}

export enum INDICATOR {
  POSITIVE = '+',
  NEGATIVE = '-',
  NEUTRAL = '',
}

export const INDICATOR_HASHMAP = {
  [SIGNAL.POSITIVE]: INDICATOR.POSITIVE,
  [SIGNAL.NEGATIVE]: INDICATOR.NEGATIVE,
  [SIGNAL.NEUTRAL]: INDICATOR.NEUTRAL,
}

export const COLOR_SCHEME_HASHMAP = {
  [SIGNAL.POSITIVE]: COLOR_SCHEME.GREEN,
  [SIGNAL.NEGATIVE]: COLOR_SCHEME.RED,
  [SIGNAL.NEUTRAL]: COLOR_SCHEME.UNIQUE_GRAY,
}
