mutation UPDATE_USER_LOCALE($userID: ID!, $locale: String!) {
  updateUserSetting(userID: $userID, key: LOCALE, value: $locale) {
    value
  }
}

query GET_USER_LOCALE($userID: ID!) {
  user(id: $userID) {
    settings(keys: [LOCALE]) {
      edges {
        node {
          value
        }
      }
    }
  }
}
