query GET_USER_KEY_RESULTS_FROM_NOT_ACTIVE_CYCLES($userID: ID!) {
  cycles(active: false) {
    edges {
      node {
        id
        period
        cadence
        active
        parent {
          id
          period
        }
        keyResults(ownerId: $userID) {
          edges {
            node {
              id
              title
              initialValue
              goal
              format
              type
              objective {
                title
              }
              owner {
                id
                firstName
                fullName
                nickname
                picture
                role
                about
                linkedInProfileAddress
                teams {
                  edges {
                    node {
                      id
                      name
                    }
                  }
                }
              }
              latestKeyResultCheckIn {
                id
                value
                confidence
                progress
                comment
                createdAt
                user {
                  fullName
                }
              }
              keyResultCheckIns {
                policy {
                  create
                }
              }
            }
          }
        }
      }
    }
  }
}
