# @deprecated in favor of GET_KEY_RESULT_AND_RELATIONS
query GET_KEY_RESULT_TIMELINE_WITH_ID($id: ID!, $first: Int, $after: Float) {
  keyResult(id: $id) {
    id
    format
    type
    timeline(first: $first, after: $after) {
      edges {
        node {
          ... on KeyResultUpdate {
            id
            createdAt
            keyResultId
            author {
              type
              identifier
            }
            patches {
              key
              value
            }
          }
          ... on KeyResultCheckIn {
            id
            value
            confidence
            progress
            comment
            createdAt
            keyResultId
            delta {
              value
            }
            user {
              id
              fullName
              picture
            }
            parent {
              confidence
              value
            }
            policy {
              delete
            }
          }
          ... on KeyResultComment {
            id
            text
            createdAt
            keyResultId
            type
            extra
            parentId
            user {
              id
              fullName
              picture
            }
            policy {
              delete
            }
          }
        }
      }
      pageInfo {
        endCursor
      }
    }
  }
}
