query GET_KEY_RESULT_TIMELINE_WITH_ID($id: ID!, $first: Int, $after: String) {
  keyResult(id: $id) {
    id
    format
    timeline(first: $first, after: $after) {
      edges {
        node {
          ... on KeyResultCheckIn {
            id
            value
            valueIncrease
            confidence
            progress
            comment
            createdAt
            keyResultId
            user {
              fullName
            }
            parent {
              confidence
              value
            }
            policy {
              delete
            }
          }

          ... on KeyResultComment {
            id
            text
            createdAt
            keyResultId
            user {
              fullName
              picture
            }
            policy {
              delete
            }
          }
        }
      }
      pageInfo {
        endCursor
      }
    }
  }
}
