query GET_KEY_RESULT_TIMELINE_WITH_ID($id: ID!, $limit: Int, $offset: Int) {
  keyResult(id: $id) {
    id
    timeline(limit: $limit, offset: $offset) {
      ... on KeyResultCheckIn {
        id
        confidence
        progress
        comment
        createdAt
        keyResultId
        user {
          fullName
        }
        parent {
          confidence
          progress
        }
        policies {
          delete
        }
      }

      ... on KeyResultComment {
        id
        text
        createdAt
        keyResultId
        user {
          fullName
          picture
        }
        policies {
          delete
        }
      }
    }
  }
}
