query GET_KEY_RESULT_WITH_ID($id: ID!) {
  keyResult(id: $id) {
    id
    title
    description
    goal
    currentProgress
    currentConfidence
    owner {
      fullName
      picture
    }
    objective {
      title
      cycle {
        name
        dateStart
        dateEnd
      }
    }
    policies {
      update
    }
    reports {
      createdAt
      comment
      user {
        fullName
        picture
      }
    }
  }
}
