query GET_KEY_RESULT_WITH_ID($id: ID!) {
  keyResult(id: $id) {
    id
    title
    description
    goal
    currentProgress
    owner {
      name
      picture
    }
    objective {
      title
      cycle {
        dateStart
        dateEnd
        createdAt
      }
    }
    confidenceReports(limit: 1) {
      id
      valueNew
    }
    policies {
      update
    }
  }
}
