query GET_USER_LIST {
  users {
    edges {
      node {
        id
        fullName
        picture
        teams {
          edges {
            node {
              id
              name
            }
          }
        }
      }
    }
  }
}