query GET_MY_TASKS($onlyUnchecked: Boolean) {
  me {
    tasks(order: {createdAt: ASC}, onlyUnchecked: $onlyUnchecked) {
      edges {
        node {
          id
          description
          state
        }
      }
    }
  }
}
