query GET_KRS_WITH_MY_CHECKMARKS($userID: ID) {
  user(id: $userID) {
    keyResultsStatus(hasUserCheckMarks: true) {
      edges {
        node {
          id
          title
          checkList(first: 1000, userId: $userID) {
            edges {
              node {
                id
                description
                state
                assignedUser {
                  id
                  fullName
                }
              }
            }
            policy {
              create
            }
          }
        }
      }
    }
  }
}
