query GET_USER_KEY_RESULTS_FROM_ACTIVE_CYCLES($userID: ID!) {
  cycles(active: true) {
    id
    period
    cadence
    parent {
      period
    }
    keyResults(ownerId: $userID) {
      id
      title
      initialValue
      goal
      format
      isOutdated
      objective {
        title
      }
      owner {
        id
        firstName
        fullName
        nickname
        picture
        role
        about
        linkedInProfileAddress
        teams {
          id
          name
        }
      }
      latestKeyResultCheckIn {
        id
        value
        confidence
        progress
        comment
        createdAt
        user {
          fullName
        }
      }
    }
  }
}
