query GET_USER_DETAILS($userId: ID) {
  user(id: $userId) {
    id
    picture
    fullName
    firstName
    role
    yearlyProgress {
      showProgress
      progress
    }
    quarterlyProgress {
      showProgress
      progress
    }
    teams {
      edges {
        node {
          name
        }
      }
    }
    policy {
      update
    }
  }
}
