query GET_USER_DETAILS($userId: ID) {
  user(id: $userId) {
    id
    picture
    fullName
    firstName
    role
    yearlyProgress
    quarterlyProgress
    teams {
      edges {
        node {
          name
        }
      }
    }
  }
}
