query GET_USERS {
  me {
    companies(first: 1) {
      edges {
        node {
          users(first: 1000, withInactives: true) {
            edges {
              node {
                id
                firstName
                nickname
                status
                linkedInProfileAddress
                about
                fullName
                role
                picture
                # TODO: do not fetch companies
                companies {
                  edges {
                    node {
                      id
                      name
                    }
                  }
                }
                # TODO: do not fetch teams
                teams {
                  edges {
                    node {
                      id
                      name
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
