query GET_COMPANY_OBJECTIVES {
  teams(filters: { onlyCompanies: true }) {
    id
    name
    gender
    objectives {
      id
      title
      progressIncreaseSinceLastWeek
      status {
        progress
        confidence
      }
    }
  }
}
