query GET_COMPANY_OBJECTIVES {
  teams(onlyCompanies: true) {
    id
    name
    gender
    objectives {
      id
      title
      progress
      confidence
      progressIncreaseSinceLastWeek
    }
  }
}
