query GET_CHECKLIST_OF_KEY_RESULT($id: ID!) {
  keyResult(id: $id) {
    id
    checkList {
      policy {
        create
      }
      progress {
        total
        numberOfChecked
        progress
      }
      edges {
        node {
          id
          description
          state
        }
      }
    }
  }
}

mutation TOGGLE_CHECK_MARK($id: ID!) {
  toggleCheckMark(data: { id: $id }) {
    id
    state
  }
}

mutation CREATE_CHECK_MARK($keyResultID: ID!, $description: String!) {
  createKeyResultCheckMark(data: { keyResultId: $keyResultID, description: $description }) {
    id
    description
    state
  }
}
