query GET_CHECKLIST_OF_KEY_RESULT($id: ID!) {
  keyResult(id: $id) {
    id
    checkList {
      policy {
        create
      }
      progress {
        total
        numberOfChecked
        progress
      }
      edges {
        node {
          id
          description
          state
          policy {
            update
          }
        }
      }
    }
  }
}

mutation TOGGLE_CHECK_MARK($id: ID!) {
  toggleCheckMark(data: { id: $id }) {
    id
    state
  }
}
